language: node_js
node_js:
  - "12.13.0"

cache:
  directories:
    - "node_modules"

branches:
  only:
    - dev

install:
  - yarn
  - yarn generate

script:
  - echo "Skipping tests"

deploy:
  provider: pages
  edge: true
  skip-cleanup: true
  github-token: $GITHUB_ACCESS_TOKEN
  target-branch: master
  local-dir: dist
  verbose: true
  on:
    branch: dev